### ISSUE TITLE
Message popups on /flagged page vanish too easily

### ISSUE THREAD

**Issue by przemoc** [alpinelinux/aports-turbo#8]
They are hidden even when I want to select the text from the message popup itself.

(Tested in Chrome 49 on Windows 7 x64)

**Comment by przemoc** [comment]
I can select text from the message now, but clicking other envelope icon doesn't hide already shown popup before showing new one. I think there is small value in having more than one message shown at once, yet it burden user with closing old one before showing new one (unless message popup mess doesn't bother her or him).

**Comment by clandmeter** [comment]
I don't see any option in bootstrap to provide what you suggest. I am open for suggestions or other solutions.
